export const RENAME_COMPONENT = 'RENAME_COMPONENT';
export const CHANGE_TYPE = 'CHANGE_TYPE';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const UPDATE_CHILDRENLIST = 'UPDATE_CHILDRENLIST';