export const RENAME_COMPONENT = "RENAME_COMPONENT";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const DELETE_COMPONENT = "DELETE_COMPONENT";
export const UPDATE_CHILDRENLIST = "UPDATE_CHILDRENLIST";
//starting here for main display container
export const SET_CURRENT_COMPONENT = "SET_CURRENT_COMPONENT";
export const SET_TRANS_AND_HISTORY = "SET_TRANS_AND_HISTORY";
export const GO_BACK_OR_FORWARD = "GO_BACK_OR_FORWARD";
export const ADD_CHILD = "ADD_CHILD";
export const DELETE_CHILD = "DELETE_CHILD";
